CREATE USER devuser WITH PASSWORD 'devpassword';
CREATE DATABASE devproject;
GRANT ALL PRIVILEGES ON DATABASE devproject TO devuser;
\c devproject
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO devuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO devuser;